# Generated by Django 5.1.5 on 2025-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_webapp', '0002_user_date_created_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(null=True)),
                ('joined_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
